/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/dervint/Desktop/Qualcomm/testing/Blosm/mdp-prototype-app/public/model.glb -o /Users/dervint/Desktop/Qualcomm/testing/Blosm/mdp-prototype-app/src/app/components/three/Model.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.None_vegetation.geometry} material={materials.vegetation} />
      <mesh geometry={nodes.None_roads_tertiary.geometry} material={materials.roads_tertiary} position={[0, 0.3, 0]} />
      <mesh geometry={nodes.None_roads_service.geometry} material={materials.roads_service} position={[0, 0.3, 0]} />
      <mesh geometry={nodes.None_roads_unclassified.geometry} material={materials.roads_unclassified} position={[0, 0.3, 0]} />
      <mesh geometry={nodes.None_paths_footway.geometry} material={materials.paths_footway} position={[0, 0.3, 0]} />
      <mesh geometry={nodes.None_water.geometry} material={materials.water} position={[0, 0.2, 0]} />
      <mesh geometry={nodes.None_forest.geometry} material={materials.forest} position={[0, 0.1, 0]} />
      <mesh geometry={nodes.None_paths_cycleway.geometry} material={materials.paths_cycleway} position={[0, 0.3, 0]} />
      <mesh geometry={nodes.None_paths_steps.geometry} material={materials.paths_steps} position={[0, 0.3, 0]} />
      <mesh geometry={nodes.None_areas_pedestrian.geometry} material={materials.areas_pedestrian} />
      <mesh geometry={nodes.None_areas_service.geometry} material={materials.areas_service} />
      <mesh geometry={nodes.None_areas_footway.geometry} material={materials.areas_footway} />
      <mesh geometry={nodes.None_buildings_1.geometry} material={materials.wall} />
      <mesh geometry={nodes.None_buildings_2.geometry} material={materials.roof} />
    </group>
  )
}

useGLTF.preload('/model.glb')
